In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.reshape(3072)

ValueError: cannot reshape array of size 3 into shape (3072,)

In [5]:
a.reshape(1)

ValueError: cannot reshape array of size 3 into shape (1,)

In [6]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [7]:
a

array([1, 2, 3])

In [8]:
b = a.reshape(3,1)

In [9]:
b

array([[1],
       [2],
       [3]])

In [10]:
a

array([1, 2, 3])

In [11]:
a,b

(array([1, 2, 3]), array([[1],
        [2],
        [3]]))

In [12]:
a


array([1, 2, 3])

In [13]:
a[1]

2

In [14]:
c = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [15]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
c[1]

array([4, 5, 6])

In [17]:
c[1,:]

array([4, 5, 6])

In [18]:
c[1,:1]

array([4])

In [19]:
c[1,:2]

array([4, 5])

In [20]:
c[1,:3]

array([4, 5, 6])

In [21]:
a

array([1, 2, 3])

In [22]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a - c

array([[ 0,  0,  0],
       [-3, -3, -3],
       [-6, -6, -6]])

In [25]:
d = np.array([[1,2,3],[4,5,6]])

In [26]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
e = np.array([1,2,3])

In [28]:
e

array([1, 2, 3])

In [29]:
e - d

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [30]:
d - e

array([[0, 0, 0],
       [3, 3, 3]])

In [31]:
np.sum(d-e)

9

In [32]:
np.sum(a - c)

-27

In [33]:
np.sum(a-c, axis=1)


array([  0,  -9, -18])

In [34]:
np.sum(a-c, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [37]:
np.sum(a-c, axis=(1,))

array([  0,  -9, -18])

In [38]:
z = np.sum(a-c, axis=(1,))

In [39]:
z

array([  0,  -9, -18])

In [45]:
dists = np.zeros((100, 500))

In [46]:
dists

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [47]:
dists = np.zeros((4,3))

In [48]:
dists

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [49]:
dists[1] = z

In [50]:
dists

array([[  0.,   0.,   0.],
       [  0.,  -9., -18.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.]])

In [51]:
np.arrange(5)

AttributeError: 'module' object has no attribute 'arrange'

In [53]:
s=np.arange(4)

In [54]:
s

array([0, 1, 2, 3])

In [55]:
s.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [56]:
s

array([0, 1, 2, 3])

In [57]:
s.reshape(3,1)

ValueError: cannot reshape array of size 4 into shape (3,1)

In [58]:
s.reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [59]:
a

array([1, 2, 3])

In [60]:
np.argsort(a)

array([0, 1, 2], dtype=int64)

In [61]:
x = np.array([3,2,1])

In [62]:
x

array([3, 2, 1])

In [63]:
np.argsort(x)

array([2, 1, 0], dtype=int64)

In [64]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
c[np.argsort(a)]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a

array([1, 2, 3])

In [67]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
c[np.argsort(x)]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [69]:
c[np.argsort(a)][:1]

array([[1, 2, 3]])

In [70]:
c[np.argsort(x)][:1]

array([[7, 8, 9]])

In [71]:
np.argsort(c)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [72]:
c[np.argsort(c)]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])